preset: laravel

linting: true

enabled:
  - alpha_ordered_imports
disabled:
  - blank_line_before_return
  - braces
  - cast_spaces
  - elseif
  - length_ordered_imports
  - not_operator_with_successor_space
  - no_unneeded_control_parentheses
  - phpdoc_summary
  - single_class_element_per_statement
  - trailing_comma_in_multiline_array
  - unary_operator_spaces
