preset: laravel

disabled:
  - blank_line_before_return
  - braces
  - cast_spaces
  - elseif
  - not_operator_with_successor_space
  - no_blank_lines_after_throw
  - no_unneeded_control_parentheses
  - phpdoc_summary
  - single_class_element_per_statement
  - trailing_comma_in_multiline_array
  - unary_operator_spaces
